# Copyright (C) 2020-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/dora/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/dora

PRODUCT_COPY_FILES += \
    vendor/sony/dora/proprietary/vendor/firmware/BCM4349B1.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4349B1.hcd \
    vendor/sony/dora/proprietary/vendor/firmware/BCM4359C0.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4359C0.hcd \
    vendor/sony/dora/proprietary/vendor/etc/firmware/touch_module_id_0x90.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/touch_module_id_0x90.img \
    vendor/sony/dora/proprietary/vendor/etc/firmware/touch_module_id_0x91.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/touch_module_id_0x91.img \
    vendor/sony/dora/proprietary/vendor/etc/firmware/touch_module_id_0x92.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/touch_module_id_0x92.img \
    vendor/sony/dora/proprietary/vendor/etc/firmware/touch_module_id_0x93.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/touch_module_id_0x93.img \
    vendor/sony/dora/proprietary/vendor/etc/firmware/touch_module_id_0x94.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/touch_module_id_0x94.img \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b00 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b01 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b02 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b03 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b04 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b05 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.b06 \
    vendor/sony/dora/proprietary/vendor/etc/firmware/tzfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzfingerprint.mdt \
    vendor/sony/dora/proprietary/vendor/lib/libpn547_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpn547_fw.so \
    vendor/sony/dora/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf
